TARGET = crypt_main
OBJECTS = crypt_main.o io_api.o
FLAGS = -Wall -fsanitize=address  -g

$(TARGET): crypt_main.o io_api.o
	   gcc $(FLAGS) -o $@ $^
clean:
	rm -f $(TARGET) $(OBJECTS)
%.o: %.c
	gcc $(FLAGS) -c $<

crypt_main.c:  cryptctl_driver.h
io_api.c: io_api.h